/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-error": "#ffffff",
                "primary": "#8f0020",
                "on-secondary": "#ffffff",
                "primary-container": "#bc002d",
                "inverse-surface": "#2e3132",
                "tertiary-container": "#775800",
                "error": "#ba1a1a",
                "on-tertiary-container": "#ffd06b",
                "primary-fixed-dim": "#ffb3b3",
                "on-primary": "#ffffff",
                "surface-tint": "#be032e",
                "tertiary-fixed": "#ffdfa0",
                "surface-container-low": "#f3f4f6",
                "surface-container-high": "#e7e8ea",
                "on-primary-container": "#ffc9c8",
                "secondary-fixed": "#d5e3ff",
                "on-background": "#191c1e",
                "on-secondary-container": "#3e5980",
                "outline": "#906f6f",
                "surface": "#f8f9fb",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#f0f1f3",
                "outline-variant": "#e4bdbc",
                "surface-container-lowest": "#ffffff",
                "surface-bright": "#f8f9fb",
                "on-secondary-fixed": "#001c3b",
                "on-primary-fixed-variant": "#920021",
                "primary-fixed": "#ffdad9",
                "on-surface": "#191c1e",
                "surface-container-highest": "#e1e2e4",
                "background": "#f8f9fb",
                "tertiary-fixed-dim": "#f6be39",
                "on-tertiary": "#ffffff",
                "on-surface-variant": "#5c403f",
                "tertiary": "#5a4100",
                "on-error-container": "#93000a",
                "secondary-container": "#b5d0fd",
                "surface-container": "#edeef0",
                "inverse-primary": "#ffb3b3",
                "on-tertiary-fixed-variant": "#5c4300",
                "surface-variant": "#e1e2e4",
                "secondary": "#455f87",
                "surface-dim": "#d9dadc",
                "on-secondary-fixed-variant": "#2d486d",
                "on-tertiary-fixed": "#261a00",
                "on-primary-fixed": "#400009",
                "secondary-fixed-dim": "#adc8f5",
                "matcha": "#4F7942",
                "indigo-custom": "#2E4482",
            },

            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },

            spacing: {
                base: "8px",
                xs: "4px",
                gutter: "20px",
                md: "24px",
                "margin-mobile": "16px",
                "max-width": "1200px",
                "margin-desktop": "auto",
                xl: "80px",
                sm: "12px",
                lg: "48px",
            },

            maxWidth: {
                "max-width": "1200px",
            },

            fontFamily: {
                "headline-lg": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "display-kanji": ["Noto Serif JP", "serif"],
                "label-md": ["Inter", "sans-serif"],
            },
        },
    },
    plugins: [],
};